In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

In [5]:
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [16]:
a.itemsize


4

In [11]:
a.size

3

In [12]:
a.size*a.itemsize

12

In [13]:
a.nbytes

12

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [18]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [19]:
a[1, 5]

13

In [20]:
a[1, -2]

13

In [21]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
a[:, 2]

array([ 3, 10])

In [23]:
a[0,1:6:2]

array([2, 4, 6])

In [24]:
a[0,1:-2:2]

array([2, 4])

In [25]:
a[0,1:-1:2]

array([2, 4, 6])

In [26]:
a[1,5]=20

In [27]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [28]:
a[:,2]=5

In [29]:
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [30]:
a[:,2]=[1,2]

In [31]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [32]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [33]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
b[0,1,1]

4

In [35]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [36]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [37]:
b[:,0,0]

array([1, 5])

In [38]:
b[:,1,:]=[[9,9],[8,8]]

In [39]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [40]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [43]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [44]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.zeros((4,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [46]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [47]:
np.full_like(a.shape,4)

array([4, 4])

In [48]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [49]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [50]:
np.random.rand(4,2)

array([[0.97763025, 0.57860775],
       [0.2605296 , 0.49121756],
       [0.60036191, 0.72108613],
       [0.86359791, 0.61409739]])

In [51]:
np.random.rand(4,2,3)

array([[[0.36018386, 0.06515805, 0.74488219],
        [0.13291118, 0.68546261, 0.89977087]],

       [[0.29477598, 0.73032314, 0.04501079],
        [0.26162195, 0.31910837, 0.16698089]],

       [[0.11815803, 0.43987619, 0.66425045],
        [0.18428209, 0.54075805, 0.46900728]],

       [[0.70550978, 0.35509107, 0.26293877],
        [0.24459613, 0.35014223, 0.67215579]]])

In [53]:
np.random.random_sample(a.shape)

array([[0.338447  , 0.59516877, 0.57646479, 0.49423436, 0.62264184,
        0.90580967, 0.91278609],
       [0.76155247, 0.86570474, 0.74639076, 0.90321006, 0.97127804,
        0.07643695, 0.50166796]])

In [55]:
np.random.randint(7)

1

In [60]:
np.random.randint(7,size=(3,3))

array([[6, 2, 5],
       [3, 3, 2],
       [5, 2, 0]])

In [61]:
np.random.randint(4,7,size=(3,3))

array([[6, 4, 5],
       [6, 4, 5],
       [5, 4, 6]])

In [62]:
np.random.randint(4,8,size=(3,3))

array([[4, 4, 7],
       [4, 5, 6],
       [5, 6, 7]])

In [63]:
np.random.randint(-4,8,size=(3,3))

array([[ 5,  3, -4],
       [-4,  6,  7],
       [ 3,  2, -4]])

In [64]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3)

In [67]:
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [68]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)

In [69]:
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [70]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)

In [71]:
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [72]:
output = np.ones((5,5))

In [73]:
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [74]:
z = np.zeros((3,3))

In [75]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
z = np.zeros((3,3))
z[1,1] = 9

In [77]:
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [79]:
output = np.ones((5,5))
output[1:4,1:4]=z

In [80]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [81]:
output = np.ones((5,5))
output[1:-1,1:-1]=z

In [82]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:
a = np.array([1,2,3])

In [84]:
a

array([1, 2, 3])

In [85]:
a = np.array([1,2,3])
b=a

In [86]:
b

array([1, 2, 3])

In [87]:
a = np.array([1,2,3])
b=a
b[0]=100

In [88]:
b

array([100,   2,   3])

In [89]:
a

array([100,   2,   3])

In [90]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

In [91]:
a

array([1, 2, 3])

In [92]:
b

array([100,   2,   3])

In [93]:
a = np.array([1,2,3,4])

In [94]:
a

array([1, 2, 3, 4])

In [95]:
a + 2

array([3, 4, 5, 6])

In [96]:
a - 2

array([-1,  0,  1,  2])

In [97]:
a * 2

array([2, 4, 6, 8])

In [98]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [99]:
b = np.array([1,0,1,0])

In [100]:
a+b

array([2, 2, 4, 4])

In [101]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [102]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [103]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [104]:
a = np.ones((2,3))

In [105]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [106]:
b = np.full((3,2), 2)

In [107]:
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [108]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [109]:
c = np.identity(3)

In [110]:
np.linalg.det(c)

1.0

In [111]:
stats = np.array([[1,2,3],[4,5,6]])

In [112]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
np.min(stats)

1

In [114]:
np.max(stats)

6

In [115]:
np.min(stats,axis=1)

array([1, 4])

In [116]:
np.min(stats,axis=0)

array([1, 2, 3])

In [117]:
np.max(stats,axis=0)

array([4, 5, 6])

In [118]:
np.max(stats,axis=1)

array([3, 6])

In [119]:
np.sum(stats)

21

In [120]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [121]:
before = np.array([[1,2,3,4],[5,6,7,8]])

In [122]:
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [123]:
before.shape

(2, 4)

In [124]:
after = before.reshape((8,1))

In [125]:
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [126]:
after = before.reshape((4,2))

In [127]:
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [128]:
after = before.reshape((2,2,2))

In [129]:
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [130]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [132]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [134]:
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [135]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [136]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

In [138]:
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [139]:
h2

array([[0., 0.],
       [0., 0.]])

In [140]:
np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])